[package]
name = "marlin-spade-macro"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
marlin-verilog-macro-builder.workspace = true
marlin-verilator.workspace = true
camino.workspace = true

proc-macro2.workspace = true
proc-macro-error.workspace = true
syn.workspace = true
quote.workspace = true

spade-common.workspace = true
spade-hir.workspace = true
spade-lang.workspace = true
spade-typeinference.workspace = true
spade-hir-lowering.workspace = true
spade-types.workspace = true

num.workspace = true
bincode.workspace = true
itertools.workspace = true
